version: "3.8"

services:
    python:
        build:
            dockerfile: ./docker/python.dockerfile
            context: .
        image: r4deu51/notification_python_clone_instagram
        container_name: notification_python_clone_instagram
        networks:
            - network
        deploy:
          x-aws-autoscaling:
            min: 1
            max: 2
            cpu: 75

networks:
    network:
        driver: bridge