version: "3.8"

services:
    nodejs:
        build: 
            dockerfile: ./docker/node.dockerfile
            context: .
        image: r4deu51/authentication_node_clone_instagram
        container_name: authentication_node_clone_instagram
        ports:
            - "3000"
        networks:
            - network
        environment:
            - NODE_ENV=production
        depends_on:
            - mongodb
        deploy:
            x-aws-autoscaling:
                min: 1
                max: 2
                cpu: 75
            # resources:
            #     limits:
            #       cpus: 0.5
            #       memory: '500Mb'
            #     reservations:
            #       cpus: 0

    mongodb:
        build: 
            dockerfile: ./docker/mongodb.dockerfile
            context: .
        image: r4deu51/authentication_mongodb_clone_instagram
        container_name: authentication_mongodb_clone_instagram
        networks:
            - network
        restart: always
        deploy:
          replicas: 1
        volumes:
            - users:/data/db

networks:
    network:
        driver: bridge
volumes:
    users:
        external: true
        name: fs-0fc58f7a0004ec4cd