version: "3.8"

services:
    nodejs:
        build: 
            dockerfile: ./docker/node-dev.dockerfile
            context: .
        image: r4deu51/resize_node_clone_instagram
        container_name: resize_node_clone_instagram
        ports:
            - "3002:3000"
        volumes:
            - ./:/app:rw
        networks:
            - network
        environment:
            - NODE_ENV=development

networks:
    network:
        driver: bridge