version: "3.8"

services:
    nodejs:
        build: 
            dockerfile: ./docker/node.dockerfile
            context: .
        image: r4deu51/publication_node_clone_instagram
        container_name: publication_node_clone_instagram
        ports:
            - "3000"
        networks:
            - network
        environment:
            - NODE_ENV=production
        depends_on:
            - mongodb
            
    nginx:
        build: 
            dockerfile: ./docker/nginx.dockerfile
            context: .
        image: r4deu51/publication_nginx_clone_instagram
        container_name: publication_nginx_clone_instagram
        ports:
            - "447:443"
        networks:
            - network

    mongodb:
        build: 
            dockerfile: ./docker/mongodb.dockerfile
            context: .
        image: r4deu51/publication_mongodb_clone_instagram
        container_name: publication_mongodb_clone_instagram
        networks:
            - network
        restart: always

networks:
    network:
        driver: bridge