version: "3.8"

services:
    nodejs:
        build: 
            dockerfile: ./docker/node.dockerfile
            context: .
        image: r4deu51/publication_node_clone_instagram
        container_name: publication_node_clone_instagram
        ports:
            - "3000"
        networks:
            - network
        environment:
            - NODE_ENV=production
    nginx:
        build: 
            dockerfile: ./docker/nginx.dockerfile
            context: .
        image: r4deu51/publication_nginx_clone_instagram
        container_name: publication_nginx_clone_instagram
        ports:
            - "443:443"
        networks:
            - network

networks:
    network:
        driver: bridge